---
default_stages: [commit]
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: https://github.com/python-poetry/poetry
    rev: "1.3.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "dev-requirements.txt", "--only", "dev", "--without-hashes"]
        verbose: true
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without", "dev", "--without-hashes"]
        verbose: true
  - repo: local
    hooks:
      - id: flake8
        name: flake8 - code lint and style checks
        entry: flake8
        language: python
        types: [python]
        args: [--config, .flake8]
      - id: isort
        name: isort - import sorting
        entry: isort
        language: python
        types: [python]
        args: [--settings-path, pyproject.toml]
      - id: black
        name: black - check formatting (show diff on FAIL)
        entry: black
        language: python
        types: [python]
        args: [--config, pyproject.toml, --check, --diff, --color, --quiet]
      - id: black
        name: black - auto-format code on FAIL
        entry: black
        language: python
        types: [python]
        args: [--config, pyproject.toml]

# https://pre-commit.ci/
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: 'main'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
